 /*khodkar c# comment 
    public partial class FirstTime : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "Dynamic.DynamicTestModels",
                c => new
                    {
                        Id = c.Int(nullable: false, identity: true),
                        Name = c.String(maxLength: 254),
                        Language = c.String(maxLength: 8),
                        CreateUserId = c.Int(),
                        ModifieUserId = c.Int(),
                        ViewCount = c.Int(nullable: false),
                        ViewRoleId = c.Int(),
                        ModifyRoleId = c.Int(),
                        AccessRoleId = c.Int(),
                        CreateLocalDateTime = c.String(maxLength: 19),
                        ModifieLocalDateTime = c.String(maxLength: 19),
                        AccessLocalDateTime = c.String(maxLength: 19),
                        CreateDateTime = c.DateTime(nullable: false),
                        ModifieDateTime = c.DateTime(nullable: false),
                        AccessDateTime = c.DateTime(nullable: false),
                        Status = c.Int(nullable: false),
                        RowVersion = c.Binary(nullable: false, fixedLength: true, timestamp: true, storeType: "rowversion"),
                    })
                .PrimaryKey(t => t.Id);
            
        }
        
        public override void Down()
        {
            DropTable("Dynamic.DynamicTestModels");
        }
    }

// <auto-generated />

    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FirstTime : IMigrationMetadata
    {
       // private readonly ResourceManager Resources = new ResourceManager(typeof(FirstTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201712211158249_FirstTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1Z227bOBB9X2D/QdBzatnJFkgDuUXqJIuguSFK87pgpLFDLEV5SSqNvq0P+0n7CzvUXZQsW4o3WBQIKopzZniG4hyO//n5t/vlNWTWCwhJIz63Z5OpbQH3o4Dy1dyO1fLDsf3l86+/uOdB+Go9FvOO9Dy05HJuPyu1PnEc6T9DSOQkpL6IZLRUEz8KHRJEzuF0+smZzRxACBuxLMu9j7miIaQP+LiIuA9rFRN2HQXAZD6Ob7wU1bohIcg18WFuf/MmZwkn6GZyRhQ59X2QcoIICl6VtK1TRglG5QFb2hbhPFJEYcwn3yV4SkR85a1xgLCHZA04b0mYhHwtJ9X0XZc1PdTLcirDAsqPpYrCgYCzo5wnxzQfxbZd8ohMniPjKtGrTtmc2zmLDyBVyrptmU5PFkxogwbp6dyJaXxgmVP+EB8Pyg0znaT/DqxFzFQsYM4hVoKg2V38xKj/DZKH6E/gcx4zVg8bA8d3jQEcuhPRGoRK7mGZL+YysC2naeeYhqVZzSZb3iVXR4e2dYPOyRODclfUqPBUJOB34CCIguCOKAWCawxIeW15N3zpv4U33Ib4ddnWNXm9Ar5Sz3P78ONvtnVBXyEoRvIIvnOKHyMaKRHDNidXhK9isupzdLwHNwsByAF+T6LFYL8h7gu6pGMsHyn8WER4aGzL2HaY+4jBmLiTEYbZ4TTCMKP4KvIJw0MOHmjv7pl92kNW8+S8q8+Mn3d1mTFrequeB+6onLW94WWM7A3Ow9Mrlm/7aO6jH/kxXuB8pZwIPPJ02Y6FQL2QXKcJSLOzy3kz4qRdROE6VmCc865T1bV2tdOqgFBEapa8XCx0FDw8mvKaJ/Pt1KQmg/VAbaihSHUVTyZCWqWyewFlqJX2cTLxU4gkZ4NKcq/Jeo3fSk015SOWl0mmxQdvuH4IMwzHlx0yooy29IRJw8pjvNVZC+CCCqm0VnsiOtWLIGxNMxKzgfTC2SbuTZlQpaKw1P/PrPtlZDtpBnZF8gWuO0QRkFIAZawd+qoFkepbwojoECaLiMUh3yRu+qwzqVG3z0Z2R6h0RB2lGt0dqSkV6mjNN7sjGhqiDmm82h2zpi7qeLXhYVhFwTfBivGBq0268JpvdkdsSpI6YvPN0BwbRbydamPC4Iz3OOieMZSTHgedE4Yy1EfOG3jppWQ8G31EjEEtlEgdrRjbHaWuRepI9fE2musYZ7VZKJxWpTCukmYJ6ivg5pTSe1nIjYLt5sVze++jVU2zKbaFNL3QQFdSL5EKwrSmTby/2IJR0AdYMeGacLrEipTdtu3D6ezQaJn8f9oXjpQBG9jDePfWAdXsbm0ODJTc9W4BfyHCfyai3S+oQMc0Bzpxj4eidvUCUkqGwXR2BkbgtPoEBsbILsHYFSVvhunqIIyA6ekndO4DfdUelcH/0kVPt2BPHrqbAwE+qz02B0bjdTcHRsM1mwNjvpR2a0BEP16Kka0X+V5vw2727XvmsIv7Tvf2rNqWxrjmLPqOLsDIK35bCbhO/bcS9wwkXVUQ+pcTDr4usRVoMeeSL6MiYbjyekTFFHPDgiKBvg0LRZfEV/ha77i0EfdIWIxTzsMnCC75bawwiadSQvjEGt1v1+n3n/YxmjG7t2v9JPexBAyT6i/iln+NKQvKuC86dtgGCL2X8m2LUXlKb99VUiLdRHxHoJy+M1gD11LgAcI1QzB5yz3yAmNiwwp5BSviJ4Wg2wyyPRFN2t0zSlaChDLHqOz173+O/gHw8791U22sMhwAAA=="; }
        }
    }

 khodkar c# comment*/ 