$.asRes = {
    en: {
        bootGrid: {
            all: "All",
            infos: "Showing {{ctx.start}} to {{ctx.end}} of {{ctx.total}} entries",
            loading: "Loading...",
            noResults: "No results found!",
            refresh: "Refresh",
            search: "Search"
        },
        //#region dropDownList
        dropDownList: {
            select: 'Please Select'
        },
        //#endregion

        //#region validate
        validate: {
            required: "Required.",
            remote: "Please correct this field.",
            email: "Please enter a correct email.",
            url: "Please enter the correct address.",
            date: "Please enter a valid date.",
            dateFA: "Please enter a valid date.",
            dateISO: "Please enter the correct date (ISO).",
            number: "Please enter the correct number.",
            digits: "Please enter only digits.",
            creditcard: "Please enter the correct credit card.",
            equalTo: "Please enter the amount of equity.",
            extension: "Please enter some ",
            maxlength: "Please do not enter more than {0} characters.",
            minlength: "Please do not enter more than {0} characters.",
            rangelength: "Please specify a value between {0} to {1} characters Enter.",
            range: "Please specify a value between {0} to {1} characters Enter.",
            max: "Please enter a value less than {0}.",
            min: "Please enter a value greater than {0}.",
            minWords: "Please enter at least {0} word.",
            maxWords: "Please enter a maximum of {0} word."
        },
        //#endregion
        title: 'Title',
        ok: 'Ok',
        save: 'Save',
        cancel: 'Cancel',
        add: "Add",
        edit: "Edit",
        dell: "Delete",
        is: 'Is',
        notIs: 'Not Is',
        waiting: 'Loading',
        info: 'Info',
        error: 'Error',
        remove:'Delete',
        message: 'Message',
        form: 'Form',
        loadComplete: 'Load Complete',
        ajaxError: 'connection Error with server',
        requireError: 'Required',
        warning: 'Warning',
        deleteRecord: 'Are you sure you delete the record ?',
        name: 'Name',
        fathername: 'Father Name',
        famillyName: 'Familly Name',
        nationalCode: 'National Code',
        address: 'Address',
        icon: 'Icon',
        role: 'Role',
        refresh: 'Refresh',
        test: 'Test',
        select: 'Select',
        personely: 'Personely',
        mobile: 'Mobile',
        tell: 'Tell',
        fileNo: 'File No',
        identity: 'Identity',
        loginSuccess: 'Login Successed',
        storageNotSupport: 'Unfortunately, your browser does not support local store',
        InvalidLogin: 'Username or password is incorrect ',
        profile: 'Profile',
        settings: 'Settings',
        logOff: 'LogOff',
        back: 'Back',
        close: 'Close',
        pleaseRetry: 'Please Retry',
        validateError: 'Please correct the information in red',
        successOpration: 'The operation ended successfully',
        accessDeny: 'Access Deny On This Page Or One Part Of This Page',
        invalidQueryString: "MisMatch QueryString",
        notFound: " Not Found! ",
        url:" Url",
        restartAppMessage:"Dear user, In order to add new features, the website will be restarted for a few seconds. Please stop your work and continue after restarting.",
        fileAlreadyExist:"The File Already Exist"
    }
};
