// <auto-generated />
namespace KS.DataAccess.ContentManagementDbContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class To24HoursFormat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(To24HoursFormat));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281504102_To24HoursFormat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
