//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KS.Core.DevelopServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigrationInfo", Namespace="http://schemas.datacontract.org/2004/07/KS.Server.Model.Migration")]
    [System.SerializableAttribute()]
    public partial class MigrationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppDataPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfigurationTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContextAssemblyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContextAssemblyPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContextAssemblyRootNameSpaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ForceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameSpaceQualifiedConnectionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebConfigPathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppDataPath {
            get {
                return this.AppDataPathField;
            }
            set {
                if ((object.ReferenceEquals(this.AppDataPathField, value) != true)) {
                    this.AppDataPathField = value;
                    this.RaisePropertyChanged("AppDataPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConfigurationTypeName {
            get {
                return this.ConfigurationTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfigurationTypeNameField, value) != true)) {
                    this.ConfigurationTypeNameField = value;
                    this.RaisePropertyChanged("ConfigurationTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Connection {
            get {
                return this.ConnectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionField, value) != true)) {
                    this.ConnectionField = value;
                    this.RaisePropertyChanged("Connection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContextAssemblyName {
            get {
                return this.ContextAssemblyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextAssemblyNameField, value) != true)) {
                    this.ContextAssemblyNameField = value;
                    this.RaisePropertyChanged("ContextAssemblyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContextAssemblyPath {
            get {
                return this.ContextAssemblyPathField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextAssemblyPathField, value) != true)) {
                    this.ContextAssemblyPathField = value;
                    this.RaisePropertyChanged("ContextAssemblyPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContextAssemblyRootNameSpace {
            get {
                return this.ContextAssemblyRootNameSpaceField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextAssemblyRootNameSpaceField, value) != true)) {
                    this.ContextAssemblyRootNameSpaceField = value;
                    this.RaisePropertyChanged("ContextAssemblyRootNameSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Force {
            get {
                return this.ForceField;
            }
            set {
                if ((this.ForceField.Equals(value) != true)) {
                    this.ForceField = value;
                    this.RaisePropertyChanged("Force");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameSpaceQualifiedConnectionType {
            get {
                return this.NameSpaceQualifiedConnectionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.NameSpaceQualifiedConnectionTypeField, value) != true)) {
                    this.NameSpaceQualifiedConnectionTypeField = value;
                    this.RaisePropertyChanged("NameSpaceQualifiedConnectionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceName {
            get {
                return this.SourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true)) {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetName {
            get {
                return this.TargetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetNameField, value) != true)) {
                    this.TargetNameField = value;
                    this.RaisePropertyChanged("TargetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebConfigPath {
            get {
                return this.WebConfigPathField;
            }
            set {
                if ((object.ReferenceEquals(this.WebConfigPathField, value) != true)) {
                    this.WebConfigPathField = value;
                    this.RaisePropertyChanged("WebConfigPath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MigrationCode", Namespace="http://schemas.datacontract.org/2004/07/KS.Server.Model.Migration")]
    [System.SerializableAttribute()]
    public partial class MigrationCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MigrationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VerboseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarningsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesignerCode {
            get {
                return this.DesignerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignerCodeField, value) != true)) {
                    this.DesignerCodeField = value;
                    this.RaisePropertyChanged("DesignerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Infos {
            get {
                return this.InfosField;
            }
            set {
                if ((object.ReferenceEquals(this.InfosField, value) != true)) {
                    this.InfosField = value;
                    this.RaisePropertyChanged("Infos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MigrationId {
            get {
                return this.MigrationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MigrationIdField, value) != true)) {
                    this.MigrationIdField = value;
                    this.RaisePropertyChanged("MigrationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Resources {
            get {
                return this.ResourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourcesField, value) != true)) {
                    this.ResourcesField = value;
                    this.RaisePropertyChanged("Resources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Verbose {
            get {
                return this.VerboseField;
            }
            set {
                if ((object.ReferenceEquals(this.VerboseField, value) != true)) {
                    this.VerboseField = value;
                    this.RaisePropertyChanged("Verbose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warnings {
            get {
                return this.WarningsField;
            }
            set {
                if ((object.ReferenceEquals(this.WarningsField, value) != true)) {
                    this.WarningsField = value;
                    this.RaisePropertyChanged("Warnings");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DevelopServiceException", Namespace="http://schemas.datacontract.org/2004/07/KS.Server.Exceptions")]
    [System.SerializableAttribute()]
    public partial class DevelopServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevelopServer.IDevlopServer")]
    public interface IDevlopServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevlopServer/GenerateMigration", ReplyAction="http://tempuri.org/IDevlopServer/GenerateMigrationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KS.Core.DevelopServer.DevelopServiceException), Action="http://tempuri.org/IDevlopServer/GenerateMigrationDevelopServiceExceptionFault", Name="DevelopServiceException", Namespace="http://schemas.datacontract.org/2004/07/KS.Server.Exceptions")]
        KS.Core.DevelopServer.MigrationCode GenerateMigration(KS.Core.DevelopServer.MigrationInfo migrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevlopServer/GenerateMigration", ReplyAction="http://tempuri.org/IDevlopServer/GenerateMigrationResponse")]
        System.Threading.Tasks.Task<KS.Core.DevelopServer.MigrationCode> GenerateMigrationAsync(KS.Core.DevelopServer.MigrationInfo migrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevlopServer/RunMigration", ReplyAction="http://tempuri.org/IDevlopServer/RunMigrationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KS.Core.DevelopServer.DevelopServiceException), Action="http://tempuri.org/IDevlopServer/RunMigrationDevelopServiceExceptionFault", Name="DevelopServiceException", Namespace="http://schemas.datacontract.org/2004/07/KS.Server.Exceptions")]
        void RunMigration(KS.Core.DevelopServer.MigrationInfo migrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevlopServer/RunMigration", ReplyAction="http://tempuri.org/IDevlopServer/RunMigrationResponse")]
        System.Threading.Tasks.Task RunMigrationAsync(KS.Core.DevelopServer.MigrationInfo migrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevlopServer/GetMigrationScript", ReplyAction="http://tempuri.org/IDevlopServer/GetMigrationScriptResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(KS.Core.DevelopServer.DevelopServiceException), Action="http://tempuri.org/IDevlopServer/GetMigrationScriptDevelopServiceExceptionFault", Name="DevelopServiceException", Namespace="http://schemas.datacontract.org/2004/07/KS.Server.Exceptions")]
        string GetMigrationScript(KS.Core.DevelopServer.MigrationInfo migrationInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDevlopServer/GetMigrationScript", ReplyAction="http://tempuri.org/IDevlopServer/GetMigrationScriptResponse")]
        System.Threading.Tasks.Task<string> GetMigrationScriptAsync(KS.Core.DevelopServer.MigrationInfo migrationInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDevlopServerChannel : KS.Core.DevelopServer.IDevlopServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DevlopServerClient : System.ServiceModel.ClientBase<KS.Core.DevelopServer.IDevlopServer>, KS.Core.DevelopServer.IDevlopServer {
        
        public DevlopServerClient() {
        }
        
        public DevlopServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DevlopServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevlopServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevlopServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KS.Core.DevelopServer.MigrationCode GenerateMigration(KS.Core.DevelopServer.MigrationInfo migrationInfo) {
            return base.Channel.GenerateMigration(migrationInfo);
        }
        
        public System.Threading.Tasks.Task<KS.Core.DevelopServer.MigrationCode> GenerateMigrationAsync(KS.Core.DevelopServer.MigrationInfo migrationInfo) {
            return base.Channel.GenerateMigrationAsync(migrationInfo);
        }
        
        public void RunMigration(KS.Core.DevelopServer.MigrationInfo migrationInfo) {
            base.Channel.RunMigration(migrationInfo);
        }
        
        public System.Threading.Tasks.Task RunMigrationAsync(KS.Core.DevelopServer.MigrationInfo migrationInfo) {
            return base.Channel.RunMigrationAsync(migrationInfo);
        }
        
        public string GetMigrationScript(KS.Core.DevelopServer.MigrationInfo migrationInfo) {
            return base.Channel.GetMigrationScript(migrationInfo);
        }
        
        public System.Threading.Tasks.Task<string> GetMigrationScriptAsync(KS.Core.DevelopServer.MigrationInfo migrationInfo) {
            return base.Channel.GetMigrationScriptAsync(migrationInfo);
        }
    }
}
