using System;

namespace KS.Core.Model.Log
{
    public class ExceptionLog
    {
        public int Id { get; set; }
        public string Error { get; set; }
        ///// <summary>
        ///// Gets the <see cref="Exception"/> instance used to initialize this
        ///// instance.
        ///// </summary>
        ///// <remarks>
        ///// This is a run-time property only that is not written or read 
        ///// during XML serialization via <see cref="ErrorXml.Decode"/> and 
        ///// <see cref="ErrorXml.Encode(Error,XmlWriter)"/>.
        ///// </remarks>

        //public Exception Exception
        //{
        //    get; set;
        //}

        ///// <summary>
        ///// Gets or sets the name of application in which this error occurred.
        ///// </summary>

        //public string ApplicationName
        //{
        //    get; set;
        //}

        ///// <summary>
        ///// Gets or sets name of host machine where this error occurred.
        ///// </summary>

        //public string HostName
        //{
        //    get; set;
        //}

        /// <summary>
        /// Gets or sets the type, class or category of the error.
        /// </summary>

        public string Type
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets the source that is the cause of the error.
        /// </summary>

        public string Source
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets a brief text describing the error.
        /// </summary>

        public string Message
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets a detailed text describing the error, such as a
        /// stack trace.
        /// </summary>

        public string Detail
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets the user logged into the application at the time 
        /// of the error.
        /// </summary>

        public string User
        {
            get; set;
        }

        public bool IsDebugMode { get; set; }
        public bool IsMobileMode { get; set; }

        /// <summary>
        /// Gets or sets the date and time at which the 
        /// error occurred.
        /// </summary>

        public DateTime Time
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets the date and time (in local time) at which the 
        /// error occurred.
        /// </summary>

        public string LocalDateTime
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets the HTTP status code of the output returned to the 
        /// client for the error.
        /// </summary>
        /// <remarks>
        /// For cases where this value cannot always be reliably determined, 
        /// the value may be reported as zero.
        /// </remarks>

        public int StatusCode
        {
            get; set;
        }

        /// <summary>
        /// Gets or sets the HTML message generated by the web host (ASP.NET) 
        /// for the given error.
        /// </summary>

        public string WebHostHtmlMessage
        {
            get; set;
        }

        ///// <summary>
        ///// Gets a collection representing the Web server variables
        ///// captured as part of diagnostic data for the error.
        ///// </summary>

        //public NameValueCollection ServerVariables
        //{
        //    get; set;
        //}

        ///// <summary>
        ///// Gets a collection representing the Web query string variables
        ///// captured as part of diagnostic data for the error.
        ///// </summary>

        //public NameValueCollection QueryString
        //{
        //   get; set; 
        //}

        ///// <summary>
        ///// Gets a collection representing the form variables captured as 
        ///// part of diagnostic data for the error.
        ///// </summary>

        //public NameValueCollection Form{ get; set; }

        ///// <summary>
        ///// Gets a collection representing the client cookies
        ///// captured as part of diagnostic data for the error.
        ///// </summary>

        //public NameValueCollection Cookies
        //{
        //    get; set; 
        //}
    }
}
