// <auto-generated />
namespace KS.DataAccess.SecurityContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeRoleGroupIdToRoleIdInLocalRoleModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeRoleGroupIdToRoleIdInLocalRoleModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201710110620226_ChangeRoleGroupIdToRoleIdInLocalRoleModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
